name: Ruby

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        # image: postgres:11
        env:
          POSTGRES_USER: lightning_marine_services
          POSTGRES_DB: lightning_marine_services_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0.3
        
    - name: Install dependent libraries
      run: sudo apt-get install libpq-dev

    - name: Bundle install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: setup databases
      env:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      RAILS_ENV: test
      run: bundle exec rake db:setup
